export const Constants = {
  GameAction: {
    NEW_GAME: 'NEW_GAME',
    CARD_CLICKED: 'CARD_CLICKED',
    ADVANCE_PLAYER_TURN: 'ADVANCE_PLAYER_TURN',
    ADVANCE_PLAYER_TURN_SUCCESS: 'ADVANCE_PLAYER_TURN_SUCCESS',
    ADVANCE_PLAYER_TURN_FAILED: 'ADVANCE_PLAYER_TURN_FAILED',
  },
};
