const minionIcons = [];
minionIcons[0] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-1.png' };
minionIcons[1] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Happy-Minion-Icon.png' };
minionIcons[2] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-5.png' };
minionIcons[3] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Minion_icon.png' };
minionIcons[4] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Minion-reading-icon.png' };
minionIcons[5] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Shy-Minion-icon.png' };
minionIcons[6] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/superman-minion-icon.png' };
minionIcons[7] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-7.png' };
minionIcons[8] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Dancing-minion-icon.png' };
minionIcons[9] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/girl-minion-icon.png' };
minionIcons[10] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/kungfu-Minion.png' };
minionIcons[11] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/happy-agnes-icon.png' };
minionIcons[12] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-3.png' };
minionIcons[13] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/evil-minion-icon.png' };
minionIcons[14] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-2.png' };
minionIcons[15] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Angry-Minion-icon.png' };
minionIcons[16] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-8.png' };
minionIcons[17] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-6.png' };
minionIcons[18] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/despicable-me-2-Minion-icon-4.png' };
minionIcons[19] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/gru-icon-2.png' };
minionIcons[20] = { url: 'https://cdn2.iconfinder.com/data/icons/despicable-me-2-minions/128/Evil-Minion-Icon-3.png' };

export { minionIcons };
